# Generated by Django 4.2.6 on 2023-10-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=3)),
                ('passout', models.CharField(max_length=4)),
                ('addr', models.CharField(max_length=100)),
                ('econtact', models.CharField(max_length=15)),
            ],
        ),
    ]
