# Generated by Django 4.2.6 on 2023-11-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_employee_age_alter_employee_econtact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='addr',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cname',
            field=models.CharField(max_length=100, verbose_name='College'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='econtact',
            field=models.IntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ename',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passout',
            field=models.IntegerField(verbose_name='Passout'),
        ),
    ]
